export { default as Navbar } from "@/components/home/navbar";
export { default as Hero } from "@/components/home/hero";
export { default as AboutMe } from "@/components/home/about/AboutMe";
export { default as SkillsSection } from "@/components/home/skills/SkillsSection";
export { default as ProjectsSection } from "@/components/home/ProjectsSection";
export { default as ExperienceSection } from "@/components/home/experience/ExperienceSection";
export { default as BlogSection } from "@/components/home/blogs/BlogSection";
export { default as SocialSection } from "@/components/home/connect/SocialSection";
export { default as Footer } from "@/components/home/Footer";
