export { default as Navbar } from "@/components/home/navbar";
export { default as Hero } from "@/components/home/hero";
export { default as AboutMe } from "@/components/home/about/AboutMe";
export { default as SkillsSection } from "@/components/home/skills/SkillsSection";
export { default as ProjectsSection } from "@/components/home/projects/ProjectsSection";
export { default as ExperienceSection } from "./experience/ExperienceSection";
export { default as BlogSection } from "./blogs/BlogSection";
export { default as ConnectSection } from "./connect/ConnectSection";
export { default as Footer } from "@/components/home/Footer";
